### ISSUE TITLE
CW2 Backdoor

### ISSUE THREAD

**Issue by thegrb93** [RyanJGray/Backdoor_Busting_2015#1]
You need to specify the workshop url because the official cw2 has never had this (I know because I review its changes every time I update it) which leads me to believe this is a backdoor added by someone who uploaded their own version of cw2 to workshop. Without specifying where you got this version of cw2, you are slandering the original author.

**Comment by MFSiNC** [comment]
You're right.
These backdoors were logged by the anticheat on my server, from clients who joined who had them in one of their mounted addons. I can't think of an easy way to tell which files are part of which mounted workshop addon, other than mounting all their .gma's manually.

I never kept logs of what files each addon players had, as all addons' data is returned together for file.Find("lua/*", "GAME") (which is how this was found)

I could port the keyword detector I found these with to a seperate addon, so people could run it against suspicious folders, if that would be useful?

**Comment by its-suun** [comment]
https://steamid.eu/profile/76561198104066675 is the profile of the steamID which gets admin. He has some other TTT Weapon addons on workshop, probably with backdoor.
