### ISSUE TITLE
BD024_ShittyBackdoor

### ISSUE THREAD

**Issue by PhoNoTheSky** [RyanJGray/Backdoor_Busting_2015#4]
who the hell stole that from me, that was my script, i posted the stuff on pastebin

**Comment by PhoNoTheSky** [comment]
where did you find it? tho

**Comment by PhoNoTheSky** [comment]
who gave you the link?

**Comment by PhoNoTheSky** [comment]
the script doesn't work anyway because, everytime its " args == "blabla" " it should be " args[1] == "blabla" "

**Comment by RyanJGray** [comment]
I found it by searching around Pastebin. You shouldn't be using the code on this database, although, it's lovely knowing that people have started abusing it already.
