### ISSUE TITLE
HAC

### ISSUE THREAD

**Issue by montypython2** [RyanJGray/Backdoor_Busting_2015#5]
Dear RyanJGray

I would like to get HAC working on my server for nostalgic reasons and the fact that it is amassing. Would you please help

Yours sincerely montypython2.

**Comment by MinIsMin** [comment]
On which system? Windows or Linux?
HAC uses many outdated things (e.g. Dropbox Desktop for saving) which makes using the old HAC system very tricky.

**Comment by montypython2** [comment]
I think the server is windows I use a host. but if that wont work with it I will get a vps.

**Comment by RyanJGray** [comment]
I'm afraid I cannot help you to get HAC working, HAC required another addon known as HSP which is not public and I do not have a copy of it. HAC will not work on any gamemode other than Sandbox however you can patch the code a bit to get it working in a sense. Sorry but I can't help you here, look through the HAC repo on my profile there should be a setup guide (Sort of) somewhere in there.

**Comment by montypython2** [comment]
Could you please past it in this chat.

**Comment by montypython2** [comment]
And try and get a copy of HSP?

**Comment by RyanJGray** [comment]
Read what I said. I don't have a copy of HSP. HeX had the only copy and I no longer have contact with him. Sorry

**Comment by montypython2** [comment]
Can you not assist patching it tho?

**Comment by RyanJGray** [comment]
HAC is around 60k lines of code. Yes I can decipher and understand most of the code, I probably can patch it but I don't have the time nor do I want to fix HAC (For obvious reasons.)  Try to fix it yourself.
